name: Check For ZAP Errors
on:
  workflow_dispatch:
  schedule:
    # Every day at 2am
    - cron:  '0 2 * * *'

jobs:
  CheckForErrors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Check For Errors: Stable"
        run: |
          # Pulls Stable from DockerHub
          docker run --rm -v $(pwd)/.github/workflows/conf:/zap/wrk/:rw -t zaproxy/zap-stable:latest zap.sh -addonupdate -addoninstall dev -dev -cmd -autorun /zap/wrk/af-check-errors.yml
      - name: "Check For Errors: Nightly"
        if: ${{ ! cancelled() }}
        run: |
          # Pulls Nightly from GHCR
          docker run --rm -v $(pwd)/.github/workflows/conf:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:nightly zap.sh -addonupdate -addoninstall dev -dev -cmd -autorun /zap/wrk/af-check-errors.yml
